name: 🙋‍♂️ [DevTutor] - Support & Feedback
description: Get help with DevTutor, report bugs, or request features.
title: '🙋‍♂️ Support & Feedback: DevTutor'
labels: ['support', 'feedback', 'question']
assignees:
  - jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="86" alt="DevTutor" src="https://github.com/jaywcjlove/jaywcjlove/assets/1680273/f15c154d-0192-48eb-8e0e-9e245ffd974a"> Please provide as much detail as possible about your support request or feedback.

        "DevTutor for SwiftUI" is an application designed to assist developers in creating exceptional apps using SwiftUI. It offers replicable code samples and corresponding UI previews to streamline your coding process. Additionally, it includes local offline access to the official Swift Programming Language documentation in both Chinese and English.

        ### Contact Information

        If you encounter any issues or need support while using our app, please feel free to contact us through the following methods:

        - **Email Support**: [kennyiseeyou@gmail.com](mailto:kennyiseeyou@gmail.com)
        - **Social Media**: [Twitter](https://twitter.com/jaywcjlove)

        We will respond to your message as soon as possible. Thank you for your support of our app!

  - type: textarea
    attributes:
      label: 🙋‍♂️ How can we help you?
      description: Describe the issue you're facing or the feature you'd like to request.
      placeholder: For example, I'm experiencing an issue with...
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "💻 Desktop"
      description: Your operating system and version.
      options:
        - macOS 15.0 (Sequoia)
        - macOS 14.0 (Sonoma)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **How can I send you a crash report for one of your apps?**

        - macOS Open Finder
        - Select Go to **Folder…** from the Go menu <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - Enter: **~/Library/Logs/DiagnosticReports**
        - In the resulting list, select all files that starts with the app name, ZIP them, and send me
        - Attach the file to this issue

  - type: textarea
    attributes:
      label: ℹ️ Additional context
      description: Add any additional information that could be helpful.
      placeholder: ex. Screenshots, steps to reproduce, etc.
    validations:
      required: false