name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "DevTutor for SwiftUI"
          description: DevTutor is an application designed to assist developers in creating exceptional apps using SwiftUI
          keywords: SwiftUI,devtutor,swift,Tutorial app,Developer,tools,Coding,document
          favicon: assets/logo.png
          logo: ./assets/logo.png
          openSource: https://github.com/jaywcjlove/devtutor
          homepage: https://wangchujiang.com/devtutor/
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          meta:
            - <meta name="author" content="Kenny Wong">
            - <meta property="og:site_name" content="<%= site %>">
            - <meta property="og:url" content="<%=homepage%><%=RESOLVE_PATH%>">
            - <meta property="og:image" content="<%=homepage%>assets/logo.png">
            - <meta property="og:type" content="application">
            - <meta property="og:title" content="<%= site %>">
            - <meta property="og:description" content="<%= description%>">
            - <meta property="twitter:image:src" content="<%=homepage%>assets/social-preview.png">
            - <meta property="twitter:site" content="@jaywcjlove">
            - <meta property="twitter:creator" content="jaywcjlove">
            - <meta property="twitter:card" content="summary_large_image">
            - <meta property="twitter:title" content="<%= site %> - <%= description%>">
            - <meta property="twitter:description" content="<%= description%>">
            - <meta name="apple-itunes-app" content="app-id=6471227008">
          menus:
            Home: index.html
            Apps: 
              url: https://wangchujiang.com/#/app
              target: __blank
            About: 
              url: https://wangchujiang.com/#/about
              target: __blank
          sideEffectFiles:
            - README.zh.md
            - terms-of-service.md
            - terms-of-service.zh.md
            - privacy-policy.md
            - privacy-policy.zh.md
          footer: |
            <a href="./terms-of-service.html" target="_blank">Terms of Service</a> • 
            <a href="./privacy-policy.html" target="_blank">Privacy Policy</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}      
          EOF

      - run: npm install idoc@1 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist