name: CI
on:
  push:
    # branches:
    # - main
    tags:
      - v*

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ env.VERSION }}
          release: true
          body: |
            <p>
              <a target="_blank" href="https://apps.apple.com/app/devtutor/id6471227008" title="DevTutor for macOS"><img alt="DevTutor for macOS" src="https://jaywcjlove.github.io/sb/download/macos.svg" height="51"></a>
              <a target="_blank" href="https://apps.apple.com/app/devtutor/id6471227008?platform=iphone" title="DevTutor for SwiftUI for iOS"><img alt="DevTutor for SwiftUI for iOS iOS" src="https://jaywcjlove.github.io/sb/download/appstore.svg" height="51"></a>
            </p>